#:schema node_modules/wrangler/config-schema.json
name = "database"
main = "src/index.ts"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]

services = [{ binding = "STORAGE", service = "storage" }]

[[d1_databases]]
binding = "DB"
database_name = "d1-virtualbox"
database_id = "617a7a88-88ac-4126-a813-12464ce8feb5"

